version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_data_test
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql-data:


